version: '3'

services:
    mariadb:
      build: requirements/mariadb
      restart: always
      image: mariadb:ymomen
      container_name: mariadb
      env_file:
        - .env
      secrets:
        - db_password
        - db_default_root_password
        - db_root_password
      expose:
      - "3306"
      networks:
        - inception_network
      volumes:
        - DB:/var/lib/mysql
    nginx:
      build: requirements/nginx
      restart: always
      image: nginx:ymomen
      container_name: nginx
      env_file:
        - .env
      ports:
        - "443:443"
      networks:
        - inception_network
      depends_on:
        - wordpress
      volumes:
        - Wordpress_volume:/var/www/html

    wordpress:
      build: requirements/wordpress
      restart: always
      image: wordpress:ymomen
      container_name: wordpress
      env_file:
        - .env
      depends_on:
        - mariadb
      expose:
        - "9000"
      networks:
        - inception_network
      volumes:
        - Wordpress_volume:/var/www/html
      secrets:
        - wordpress_admin_password
        - wordpress_user_password
        - db_password
        - db_default_root_password
      





networks:
    inception_network:
      name: inception_network
      driver: bridge

volumes:
    DB:
      driver: local
      driver_opts:
        type: none
        device: /home/ymomen/data/DB
        o: bind
    Wordpress_volume:
      driver: local
      driver_opts:
        type: none
        device: /home/ymomen/data/Wordpress_volume
        o: bind


# configs:


secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_default_root_password:
    file: ../secrets/db_default_root_password.txt
  wordpress_admin_password:
    file: ../secrets/wordpress_admin_password.txt
  wordpress_user_password:
    file: ../secrets/wordpress_user_password.txt     