# version: '3'

services:
    mariadb:
      build: requirements/mariadb
      restart: always
      image: mariadb:ymomen
      container_name: mariadb
      env_file:
        - .env
      secrets:
        - db_password
        - db_default_root_password
        - db_root_password
      expose:
      - "3306"
      networks:
        - inception_network
      volumes:
        - DB:/var/lib/mysql
    nginx:
      build: requirements/nginx
      restart: always
      image: nginx:ymomen
      container_name: nginx
      env_file:
        - .env
      ports:
        - "443:443"
      networks:
        - inception_network
      depends_on:
        - wordpress
      volumes:
        - Wordpress_volume:/var/www/html

    wordpress:
      build: requirements/wordpress
      restart: always
      image: wordpress:ymomen
      container_name: wordpress
      env_file:
        - .env
      depends_on:
        - mariadb
      expose:
        - "9000"
      networks:
        - inception_network
      volumes:
        - Wordpress_volume:/var/www/html
      secrets:
        - wordpress_admin_pass
        - wordpress_user_pass
        - db_password
        - db_default_root_password

    redis:
      build: requirements/bonus/redis
      restart: always
      image: redis:ymomen
      container_name: redis
      depends_on:
        - wordpress
      networks: 
        - inception_network
      expose:
        - "6379"

    ftp_server:
      build: requirements/bonus/ftp_server
      restart: always
      image: ftp_server:ymomen
      container_name: ftp_server
      depends_on:
        - wordpress
      networks:
        - inception_network
      ports:
        - "21:21"
        - "20:20"
        - "21080-21090:21080-21090"
      volumes:
        - Wordpress_volume:/var/www/html
      env_file:
        - .env
      secrets:
        - ftp_server_pass

    static_site:
      build: requirements/bonus/static_site
      restart: always
      image: static_site:ymomen
      container_name: static_site
      env_file:
        - .env
      ports:
        - "1999:1999"
      networks:
        - inception_network

    adminer:
      build: requirements/bonus/adminer
      restart: always
      image: adminer:ymomen
      container_name: adminer
      env_file:
        - .env
      ports:
        - "4040:4040"
      networks:
        - inception_network
      depends_on:
        - mariadb

    portainer:
      build: requirements/bonus/portainer
      restart: always
      image: portainer:ymomen
      container_name: portainer
      env_file:
        - .env
      ports:
        - "7878:7878"
        - "9443:9443"
      networks:
        - inception_network
      depends_on:
        - mariadb
        - nginx
        - wordpress
        - adminer
        - static_site
        - redis
        - ftp_server
      secrets:
        - portainer_usr_pass
      volumes:
      - portainer_data:/data 
      - /var/run/docker.sock:/var/run/docker.sock
      



networks:
    inception_network:
      name: inception_network
      driver: bridge

volumes:
    DB:
      driver: local
      driver_opts:
        type: none
        device: /home/ymomen/data/DB
        o: bind
    Wordpress_volume:
      driver: local
      driver_opts:
        type: none
        device: /home/ymomen/data/Wordpress_volume
        o: bind
    portainer_data:
      driver: local
      driver_opts:
        type: none
        device: /home/ymomen/data/portainer_data
        o: bind

# configs:


secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_default_root_password:
    file: ../secrets/db_default_root_password.txt
  wordpress_admin_pass:
    file: ../secrets/wordpress_admin_pass.txt
  wordpress_user_pass:
    file: ../secrets/wordpress_user_pass.txt
  ftp_server_pass:
    file : ../secrets/ftp_server_pass.txt
  portainer_usr_pass:
    file : ../secrets/portainer_usr_pass.txt