FROM debian:bullseye

RUN apt update && apt upgrade -y && apt install -y mariadb-server

WORKDIR /tools

COPY conf/confg.conf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY tools/script.sh script.sh

RUN mkdir -p /var/lib/mysql && mkdir -p /run/mysqld

RUN chmod +x script.sh

EXPOSE 3306

ENTRYPOINT [ "/tools/script.sh" ]